from PyQt5.QtWidgets import QWidget, QLabel, QSpinBox, QLineEdit, QGridLayout, QVBoxLayout, QCheckBox, QHBoxLayout, \
    QComboBox, QPushButton


class Config(QWidget):
    def __init__(self, parent=None):
        super(Config, self).__init__(parent)

        self.lbl_config_string = QLabel('Get list encrypted string')
        self.lbl_config_string.setStyleSheet('font-weight: bold; font-size: 18pt;')
        self.sp_length = QSpinBox(minimum=3, maximum=100, value=3)
        self.sp_maximum_items = QSpinBox(minimum=3, maximum=100, value=3)
        self.led_first_address = QLineEdit()
        self.led_first_address.setPlaceholderText('First address')
        self.led_last_address = QLineEdit()
        self.led_last_address.setPlaceholderText('Last address')
        self.lbl_length = QLabel('Length')
        self.lbl_maximum_items = QLabel('Maximum')
        self.layout_option_string = QGridLayout()
        self.layout_option_string.addWidget(self.lbl_length, 0, 0)
        self.layout_option_string.addWidget(self.sp_length, 0, 1)
        self.layout_option_string.addWidget(self.lbl_maximum_items, 1, 0)
        self.layout_option_string.addWidget(self.sp_maximum_items, 1, 1)
        self.layout_option_string.addWidget(self.led_first_address, 0, 2)
        self.layout_option_string.addWidget(self.led_last_address, 1, 2)
        self.layout_config_string = QVBoxLayout()
        self.layout_config_string.addWidget(self.lbl_config_string)
        self.layout_config_string.addLayout(self.layout_option_string)

        self.layout_section = QVBoxLayout()
        self.lbl_section = QLabel('Section')
        self.lbl_section.setStyleSheet('font-weight: bold; font-size: 14pt;')
        self.chk_data = QCheckBox('.data/.rdata')
        self.chk_text = QCheckBox('.text')
        self.chk_resource = QCheckBox('.resource')
        self.chk_custom = QCheckBox('Custom')
        self.layout_chk_section = QGridLayout()
        self.layout_chk_section.addWidget(self.chk_data, 0, 0)
        self.layout_chk_section.addWidget(self.chk_text, 1, 0)
        self.layout_chk_section.addWidget(self.chk_resource, 0, 1)
        self.layout_chk_section.addWidget(self.chk_custom, 1, 1)
        self.layout_section.addWidget(self.lbl_section)
        self.layout_section.addLayout(self.layout_chk_section)

        self.layout_string_literals = QHBoxLayout()
        self.lbl_string_literals = QLabel('String literals')
        self.cmb_string_literals = QComboBox()
        self.cmb_string_literals.addItems(['C-style (8 bits)', 'Unicode C-style (16 bits)', 'Delphi', 'Golang'])
        self.layout_string_literals.addWidget(self.lbl_string_literals)
        self.layout_string_literals.addWidget(self.cmb_string_literals)

        self.layout_button = QVBoxLayout()
        self.btn_get_list = QPushButton('Get list')
        self.btn_clear = QPushButton('Clear')
        self.btn_fill_up = QPushButton('Fill up')
        self.layout_button.addWidget(self.btn_get_list)
        self.layout_button.addWidget(self.btn_clear)
        self.layout_button.addWidget(self.btn_fill_up)

        self.layout = QVBoxLayout()
        self.layout.addLayout(self.layout_config_string, stretch=2)
        self.layout.addLayout(self.layout_section, stretch=2)
        self.layout.addLayout(self.layout_string_literals, stretch=1)
        self.layout.addLayout(self.layout_button, stretch=1)
        self.layout.addStretch(stretch=15)
        self.setLayout(self.layout)
